### ISSUE TITLE
Default language English should refer to English page properties instead of French

### ISSUE THREAD

**Issue by Chhunlong** [TYPO3-Documentation/t3SphinxThemeRtd#35]
![capture 2016-12-04 at 15 43 38](https://cloud.githubusercontent.com/assets/13775865/21419955/6e53846a-c85d-11e6-9944-d6cd95d9de7c.png)

**Comment by marble** [comment]
Hello Chhunlong, thanks for reporting. Note that THIS repo is for issues about the THEME (rendering, layout, ...) of the documentation. The right place would be the repo of the respective manual, like "Editors Tutorial" in this case. See the "Edit me on Github" button.

But in this case: We are aware of the error. It's due to the current rendering chain. Will hopefully be fixed soon. As usual: The documentation team has very little manpower ... So your report has been heard - it'll only take a moment.
