### ISSUE TITLE
Tables are sometimes broken

### ISSUE THREAD

**Issue by sascha-egerer** [TYPO3-Documentation/t3SphinxThemeRtd#56]
Tables float sometimes inside the previous one.
Example:
https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Page/Index.html#shortcuticon
![bildschirmfoto 2017-11-27 um 10 19 14](https://user-images.githubusercontent.com/1651414/33259306-c1e1fb9c-d35c-11e7-8aab-5bed56823cd8.png)

It looks like there is already a class to clear the column (`cc`) but it has no styles.

Adding a 
```
.cc { clear: both }
```
does fix the problem.

**Comment by marble** [comment]
Those contents were real tables in the OpenOffice documents. When moving them to html we gave up real real tables and are using definition lists that look a bit like the original tables but are (more) responsive. Initially that was only planned as a temporary workaround. But since then nobody has invented something better und people prefer that view to real tables or pure definition lists like https://docs.typo3.org/typo3cms/TyposcriptReference/DataTypes/Align/Index.html So we just keep it for the moment and observe the "amazing float effects" that sometimes occurr.

Note: You are in no way forced to use that format in your own manuals. It's just the other way around: Everybody is encouraged to invent something that does the job better!

**Comment by sascha-egerer** [comment]
@marble But wouldn't it be a quick win to add just the mentioned css? That would fix the issue with no side effect as far as i can see. And the problem is that this is the official documentation that is broken.

**Comment by marble** [comment]
Ah, sorry, I misunderstood the problem. Let me see again.

**Comment by marble** [comment]
Yes, thank you very much for reporting and providing a suggestion. I'll care about this issue next time when I work on the theme. It's nice for me to see people really care!

**Comment by marble** [comment]
See also https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/52

**Comment by marble** [comment]
Implement with v3.6.14
