### ISSUE TITLE
Too many different types of highlighted boxes like attention, important etc.

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#68]
Example: https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/BugfixingAZ/Index.html

Looks kind of messy to me.

IMHO it would be enough to have only 1 for:

- **attention** / **important** (keep important because it's red which kind of makes sense)
- **hint** / **tip**

**Comment by marble** [comment]
Let's keep that. (1) There ARE slight differences. (2) It doesn't hurt. (3) It just keeps what Sphinx is giving us anyway. See http://www.sphinx-doc.org/en/master/rest.html#directives

**Comment by DanielSiepmann** [comment]
I'm still with @sypets and @marble.
We should style what's already provided by Sphinx to prevent "broken" output.
But we should try to avoid using different nearly same directives. Otherwise we will just confuse readers. But that should be done bu authors and during pull requests? So more a best practice I think.
